### ISSUE TITLE
Could you please add setup process in README.md?

### ISSUE THREAD

**Issue by sihaiyang0215** [OHDSI/Criteria2Query#13]
I would like to run Criteria2Query locally but I don't find the setup process. 
Could you please add it for new user?

Thanks!

**Comment by bevankoopman** [comment]
Indeed! A small how to guide would be great as there are no details on how to run locally. Thanks.

**Comment by iamyihwa** [comment]
Thanks for the great tool! Yes in the paper it is mentioned that it can run in interactive and automated mode, however it is not easy to find out how to run it in automated mode, it would be good to add those as well!
