### ISSUE TITLE
Testing Crohn's Disease criteria

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Criteria2Query#2]
**Tested language:** 1. Be a man or woman >=18 years of age. 2. Have Crohn’s disease or fistulizing Crohn’s disease of at least 3 months’ duration, with colitis, ileitis, or ileocolitis, confirmed at any time in the past by radiography, histology, and/or endoscopy. 

**Result:** http://www.ohdsi.org/web/atlas/#/cohortdefinition/1747096 

**Result Discussion:** 1. C2Q missed the age criteria. 2. C2Q included colitis, ileitis, or ileocolitis, confirmed at any time in the past by radiography, histology, and/or endoscopy in the initial event cohort. We would have included it in the Add initial event inclusion criteria and used a nested criteria to incorporate the radiography and endoscopy criteria linked to the colitis, ileitis, or ileocolitis criteria.

**Request:** Can C2Q please include the age criteria and parse the additional criteria into the Add initial event inclusion criteria section and utilize linked concepts?

**Comment by chiyuan1126** [comment]
@jhardin29 Could you give you expectation of cohort identification? So that I could know how should I link demographic attribute. You prefer to link that age attribute to only one criterion right? or you prefer to use age as a Demographic stand alone criterion? Thanks very much!

**Comment by jhardin29** [comment]
hi @chiyuan1126 we usually link the demographic criteria to the initial event criteria but your suggestion of including a stand alone demographic criteria could work in the initial event criteria if the former is difficult to implement.

**Comment by chiyuan1126** [comment]
@jhardin29  Thanks for the information! I will fix it as soon as possible
