### ISSUE TITLE
Reset button needs to remove date range and continuous observation entries

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Criteria2Query#3]
## Expected behavior
Clicking Reset button in C2Q screen will remove all entries made in previous session.

## Actual behavior
The Reset button only removes the text made in the initial events box.

## Suggested fix
The Reset button resets all options to default options.

**Comment by chiyuan1126** [comment]
Thanks for your suggestions. I will fix it!

**Comment by chiyuan1126** [comment]
@jhardin29 Thanks for your suggestion, I will fix it.

**Comment by chiyuan1126** [comment]
@jhardin29 That bug has been fixed in version 0.8.2.2.
