### ISSUE TITLE
Testing ConceptSet Recommendation Feature - do not present identical versions of concepts

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Criteria2Query#4]
## Expected behavior
C2Q ConceptSet Recommendation presents non identical versions of concept sets to consider

## Actual behavior
C2Q ConceptSet Recommendation presents multiple identical versions of concept sets to consider

## Suggested fix
Present unique versions of concept sets to consider

**Comment by chiyuan1126** [comment]
@jhardin29 I fixed it. Now I filtered concept by their names.
I will further update by comparing the set of concepts in each set and only keep the unique one even though they may have different concept set names.
