### ISSUE TITLE
Add connector to ClinicalTrials.gov

### ISSUE THREAD

**Issue by ChunhuaWeng** [OHDSI/Criteria2Query#5]
Would be nice to add a NCTID entry box to automatically grab inclusion and exclusion criteria directly from ClinicalTrials.gov to population your first page.

**Comment by jhardin29** [comment]
If this could be extended to be able to import directly from a .pdf or .docx or .txt file to automatically grab inclusion and exclusion criteria that would be a helpful enhancement.
