### ISSUE TITLE
Change default for the naming convention for C2Q cohort created

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Criteria2Query#8]
**Observed Behavior**
Use C2Q to create a cohort, the example of a cohort named is: criteria2query_2018_05_03_12_51 which is lengthy and the description is non specific. 

**Desired Behavior**
C2Q can create the cohort and the default name in ATLAS could be changed to something more descriptive to the end user. The user could either type it in the C2Q environment directly or the default naming convention could be something like: [C2Q] followed by whatever the initial event contains, for example [C2Q] Tofacitinib_v1.0 - and increment the version number accordingly. 

**Steps to Reproduce**
NA

**Comment by chiyuan1126** [comment]
Fixed it! Since ATLAS allow different cohorts to use a same cohort name, I didn't add "_v1.0". Feel free to let me know if you think that should be added.
